const express = require("express");

const nodemailer = require("nodemailer");

let app = express();
app.use(express.json());

const cors = require("cors");
require("dotenv").config();
const allowedOrigins = ["http://127.0.0.1:3000"];

app.use(
  cors({
    origin: allowedOrigins,
    methods: ["POST", "GET"],
    credentials: true,
  })
);

const currentDate = new Date().toLocaleString("en-US", {
  weekday: "short",
  year: "numeric",
  month: "long",
  day: "numeric",
  hour: "2-digit",
  minute: "2-digit",
});
const currentYear = new Date().getFullYear();

const htmlTemplate = `
  <!DOCTYPE html>
<html lang="en" style="margin:0; padding:0;">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>New Portfolio Message</title>
  </head>
  <body style="font-family: Arial, sans-serif; background-color:#f6f9fc; margin:0; padding:20px;">
    <table width="100%" cellspacing="0" cellpadding="0" style="max-width:600px; margin:auto; background:#ffffff; border-radius:10px; box-shadow:0 2px 6px rgba(0,0,0,0.1);">
      <tr>
        <td style="background-color:#0d6efd; color:#ffffff; text-align:center; padding:20px 10px; border-radius:10px 10px 0 0;">
          <h2 style="margin:0;">💬 New Message from Your Portfolio</h2>
        </td>
      </tr>

      <tr>
        <td style="padding:20px;">
          <p style="font-size:16px; margin-bottom:10px;">Hello 👋,</p>
          <p style="font-size:15px; color:#333333;">
            You’ve received a new message from your portfolio contact form.
          </p>

          <table width="100%" cellspacing="0" cellpadding="8" style="margin-top:20px;">
            <tr>
              <td width="30%" style="font-weight:bold; color:#0d6efd;">Name:</td>
              <td>${{username}}</td>
            </tr>
            <tr>
              <td width="30%" style="font-weight:bold; color:#0d6efd;">Email:</td>
              <td>${{email}}</td>
            </tr>
            <tr>
              <td width="30%" style="font-weight:bold; color:#0d6efd;">Subject:</td>
              <td>${{subject}}</td>
            </tr>
            <tr>
              <td width="30%" style="font-weight:bold; color:#0d6efd;">Message:</td>
              <td>${{message}}</td>
            </tr>
          </table>

          <p style="margin-top:30px; font-size:14px; color:#666;">
            📅 Sent on: <strong>${{currentDate}}</strong>
          </p>
        </td>
      </tr>

      <tr>
        <td style="background-color:#f0f4f8; text-align:center; padding:15px; border-radius:0 0 10px 10px; color:#777;">
          <p style="margin:0; font-size:13px;">
            This email was automatically generated by your portfolio site.<br>
            &copy; ${{currentYear}} Sujeet Kumar — All rights reserved.
          </p>
        </td>
      </tr>
    </table>
  </body>
</html>


    `;

const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST,
  port: process.env.EMAIL_PORT,
  secure: false, // true for 465, false for other ports
  auth: {
    user: process.env.AUTH_EMAIL,
    pass: process.env.AUTH_PASSWORD,
  },
});

app.post("/send", async (req, res) => {
  const info = await transporter.sendMail({
    from: `"Enquiry mail from portfolio"  <${process.env.AUTH_EMAIL}>`,
    to: "sujeetk07555@gmail.com",
    subject: `Portfolio Contact: ${req.body.subject}`, // Subject line
    // text: "Hello world?", // plain‑text body
    html: htmlTemplate, // HTML body
  });

  console.log("Message sent:", info.messageId);
  res.send("email send");
});

app.listen(process.env.PORT, () => {
  console.log("server is running");
});


// `<table>
//              <tr>
//                  <td>Name</td>
//                  <td>${req.body.username}</td>
//              </tr>
//              <tr>
//                  <td>Email:-</td>
//                  <td>${req.body.email}</td>
//              </tr>
//              <tr>
//                  <td>Subject:-</td>
//                  <td>${req.body.subject}</td>
//              </tr>
//              <tr>
//                  <td>Message:-</td>
//                  <td>${req.body.message}</td>
//              </tr>
//          </table>`